GET HTTP://localhost:5000/countries HTTP/1.1
Content-Type: application/json



GET HTTP://localhost:5000/cities/2 HTTP/1.1



GET HTTP://localhost:5000/cities HTTP/1.1
Content-Type: application/json



DELETE HTTP://localhost:5000/countries/7 HTTP/1.1
Content-Type: application/json









